name: GitHub Actions linter
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    name: "Lint GitHub Actions workflows"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_level: error
          level: warning
          reporter: github-pr-check
